# Трехмерная визуализация 

In [2]:
from scipy.integrate import solve_ivp
import numpy as np
import sympy as sm
import sympy.physics.mechanics as me

In [3]:
class ReferenceFrame(me.ReferenceFrame):

    def __init__(self, *args, **kwargs):

        kwargs.pop('latexs', None)

        lab = args[0].lower()
        tex = r'\hat{{{}}}_{}'

        super(ReferenceFrame, self).__init__(*args,
                                             latexs=(tex.format(lab, 'x'),
                                                     tex.format(lab, 'y'),
                                                     tex.format(lab, 'z')),
                                             **kwargs)
me.ReferenceFrame = ReferenceFrame

В этой главе будет базовое введение в создание трехмерных визуализации движения. Есть много инструментов для создания интерактивной трехмерной графики из от классических инструментов нижнего уровня, таких как [OpenGL](https://en.wikipedia.org/wiki/OpenGL) до графических пользовательских интерфейсов для рисования и анимации 3D-моделей, таких как [Blender](https://en.wikipedia.org/wiki/Blender_(software)). 

Мы будем использовать [pythreejs](https://pythreejs.readthedocs.io/en/stable/), питон-враппер для  [javascript-библиотеки Three.js](https://threejs.org/), построенной на [WebGL](https://en.wikipedia.org/wiki/WebGL).

Снова используем этот пример:

![](figures/eom-double-rod-pendulum.svg)


In [4]:
m, g, kt, kl, l = sm.symbols('m, g, k_t, k_l, l')
q1, q2, q3 = me.dynamicsymbols('q1, q2, q3')
u1, u2, u3 = me.dynamicsymbols('u1, u2, u3')

N = me.ReferenceFrame('N')
A = me.ReferenceFrame('A')
B = me.ReferenceFrame('B')

A.orient_axis(N, q1, N.z)
B.orient_axis(A, q2, A.x)

A.set_ang_vel(N, u1*N.z)
B.set_ang_vel(A, u2*A.x)

O = me.Point('O')
Ao = me.Point('A_O')
Bo = me.Point('B_O')
Q = me.Point('Q')

Ao.set_pos(O, l/2*A.x)
Bo.set_pos(O, l*A.x)
Q.set_pos(Bo, q3*B.y)

O.set_vel(N, 0)
Ao.v2pt_theory(O, N, A)
Bo.v2pt_theory(O, N, A)
Q.set_vel(B, u3*B.y)
Q.v1pt_theory(Bo, N, B)

t = me.dynamicsymbols._t

qdot_repl = {q1.diff(t): u1,
             q2.diff(t): u2,
             q3.diff(t): u3}

Q.set_acc(N, Q.acc(N).xreplace(qdot_repl))

R_Ao = m*g*N.x
R_Bo = m*g*N.x + kl*q3*B.y
R_Q = m/4*g*N.x - kl*q3*B.y
T_A = -kt*q1*N.z + kt*q2*A.x
T_B = -kt*q2*A.x

I = m*l**2/12
I_A_Ao = I*me.outer(A.y, A.y) + I*me.outer(A.z, A.z)
I_B_Bo = I*me.outer(B.x, B.x) + I*me.outer(B.z, B.z)

points = [Ao, Bo, Q]
forces = [R_Ao, R_Bo, R_Q]
masses = [m, m, m/4]

frames = [A, B]
torques = [T_A, T_B]
inertias = [I_A_Ao, I_B_Bo]

Fr_bar = []
Frs_bar = []

for ur in [u1, u2, u3]:

    Fr = 0
    Frs = 0

    for Pi, Ri, mi in zip(points, forces, masses):
        vr = Pi.vel(N).diff(ur, N)
        Fr += vr.dot(Ri)
        Rs = -mi*Pi.acc(N)
        Frs += vr.dot(Rs)

    for Bi, Ti, Ii in zip(frames, torques, inertias):
        wr = Bi.ang_vel_in(N).diff(ur, N)
        Fr += wr.dot(Ti)
        Ts = -(Bi.ang_acc_in(N).dot(Ii) +
               me.cross(Bi.ang_vel_in(N), Ii).dot(Bi.ang_vel_in(N)))
        Frs += wr.dot(Ts)

    Fr_bar.append(Fr)
    Frs_bar.append(Frs)

Fr = sm.Matrix(Fr_bar)
Frs = sm.Matrix(Frs_bar)

q = sm.Matrix([q1, q2, q3])
u = sm.Matrix([u1, u2, u3])
p = sm.Matrix([g, kl, kt, l, m])

qd = q.diff(t)
ud = u.diff(t)

ud_zerod = {udr: 0 for udr in ud}

Mk = -sm.eye(3)
gk = u

Md = Frs.jacobian(ud)
gd = Frs.xreplace(ud_zerod) + Fr

eval_eom = sm.lambdify((q, u, p), [Mk, gk, Md, gd])

def eval_rhs(t, x, p):
    """Return the right hand side of the explicit ordinary differential
    equations which evaluates the time derivative of the state ``x`` at time
    ``t``.

    Parameters
    ==========
    t : float
       Time in seconds.
    x : array_like, shape(6,)
       State at time t: [q1, q2, q3, u1, u2, u3]
    p : array_like, shape(5,)
       Constant parameters: [g, kl, kt, l, m]

    Returns
    =======
    xd : ndarray, shape(6,)
        Derivative of the state with respect to time at time ``t``.

    """

    # unpack the q and u vectors from x
    q = x[:3]
    u = x[3:]

    # evaluate the equations of motion matrices with the values of q, u, p
    Mk, gk, Md, gd = eval_eom(q, u, p)

    # solve for q' and u'
    qd = np.linalg.solve(-Mk, np.squeeze(gk))
    ud = np.linalg.solve(-Md, np.squeeze(gd))

    # pack dq/dt and du/dt into a new state time derivative vector dx/dt
    xd = np.empty_like(x)
    xd[:3] = qd
    xd[3:] = ud

    return xd

q_vals = np.array([
    np.deg2rad(25.0),  # q1, rad
    np.deg2rad(5.0),  # q2, rad
    0.1,  # q3, m
])

u_vals = np.array([
    0.1,  # u1, rad/s
    2.2,  # u2, rad/s
    0.3,  # u3, m/s
])

p_vals = np.array([
    9.81,  # g, m/s**2
    3.0,  # kl, N/m
    0.01,  # kt, Nm/rad
    0.6,  # l, m
    1.0,  # m, kg
])

x0 = np.empty(6)
x0[:3] = q_vals
x0[3:] = u_vals

fps = 20
t0, tf = 0.0, 10.0
ts = np.linspace(t0, tf, num=int(fps*(tf - t0)))
result = solve_ivp(eval_rhs, (t0, tf), x0, args=(p_vals,), t_eval=ts)
xs = result.y.T

In [5]:
ts.shape, xs.shape

((200,), (200, 6))

### pythreejs

`pythreejs` позволяет вам использовать `three.js` через Python. 

Функции и объекты, которые pythreejs доступны в [его документации](https://pythreejs.readthedocs.io), но поскольку эти иметь сопоставление 1:1 с кодом Three.js, вы также найдете более полную информацию информация в [документации ThreeJS](https://threejs.org/docs/index.html). 


In [6]:
import pythreejs as p3js

pythreejs имеет множество [примитивных геометрических фигур](https://pythreejs.readthedocs.io/en/stable/examples/Geometries.html), например [`CylinderGeometry`](https://pythreejs.readthedocs.io/en/stable/api/geometries/CylinderGeometry_autogen.html#pythreejs.CylinderGeometry) может быть использован для создания цилиндров и конусов:

In [7]:
cyl_geom = p3js.CylinderGeometry(radiusTop=2.0, radiusBottom=10.0, height=50.0)
cyl_geom

CylinderGeometry(height=50.0, radiusBottom=10.0, radiusTop=2.0)

Изображение выше является интерактивным; для щелчка можно использовать мышь или трекпад, удерживайте и переместите объект.

Если вы хотите применить материал к поверхности геометрии, вы создаете [`Mesh`](https://pythreejs.readthedocs.io/en/stable/api/objects/Mesh_autogen.html#pythreejs.Mesh)который связывает [`Material`](https://pythreejs.readthedocs.io/en/stable/api/materials/Material_autogen.html#pythreejs.Material")с геометрией. 

Раскрасим цилиндр выше так:

In [8]:
red_material = p3js.MeshStandardMaterial(color='red')

cyl_mesh = p3js.Mesh(geometry=cyl_geom, material=red_material)

cyl_mesh

Mesh(geometry=CylinderGeometry(height=50.0, radiusBottom=10.0, radiusTop=2.0), material=MeshStandardMaterial(a…

### Создание сцены

Здесь я создаю новый оранжевый цилиндр, который смещен от начала координат. 

Cцена и имеет свои собственные оси координат. [`AxesHelper`](https://pythreejs.readthedocs.io/en/stable/api/helpers/AxesHelper_autogen.html#pythreejs.AxesHelper) создает простые X (красный), Y (зеленый) и Z (синий) прикреплен к сетке. 

[`position`](https://pythreejs.readthedocs.io/en/stable/api/core/Object3D_autogen.html#pythreejs.Object3D.position ) переопределено для установки позиции.

In [9]:
cyl_geom = p3js.CylinderGeometry(radiusTop=0.1, radiusBottom=0.5, height=2.0)
cyl_material = p3js.MeshStandardMaterial(color='orange', wireframe=True)
cyl_mesh = p3js.Mesh(geometry=cyl_geom, material=cyl_material)
axes = p3js.AxesHelper()
cyl_mesh.add(axes)
cyl_mesh.position = (3.0, 3.0, 3.0)

Теперь мы создадим [`Scene`](https://pythreejs.readthedocs.io/en/stable/api/scenes/Scene_autogen.html#pythreejs.Scene) который может содержать несколько сеток и других объектов, таких как источники света, камеры и оси. 

Eсть изрядное количество стандартного кода для создания статической сцены. 

Все объекты должны быть добавлены в ключевой аргумент `Scene` `children=`. 

Последняя строка создает [`WebGLBufferRenderer`](https://pythreejs.readthedocs.io/en/stable/api/renderers/webgl/WebGLBufferRenderer_autogen.html#pythreejs.WebGLBufferRenderer) который связывает камеру вид на сцену и позволяет [`OrbitControls`](https://pythreejs.readthedocs.io/en/stable/api/controls/OrbitControls_autogen.html#pythreejs.OrbitControls) разрешить масштабирование, панорамирование и вращение с помощью мыши или трекпада.


In [10]:
view_width = 600
view_height = 400

camera = p3js.PerspectiveCamera(position=[10.0, 10.0, 10.0],
                                aspect=view_width/view_height)
dir_light = p3js.DirectionalLight(position=[0.0, 10.0, 10.0])
ambient_light = p3js.AmbientLight()

axes = p3js.AxesHelper()
scene = p3js.Scene(children=[cyl_mesh, axes, camera, dir_light, ambient_light])
controller = p3js.OrbitControls(controlling=camera)
renderer = p3js.Renderer(camera=camera,
                        scene=scene,
                        controls=[controller],
                        width=view_width,
                        height=view_height)

Теперь отобразим сцену, вызвав рендерер: 

In [11]:
renderer

Renderer(camera=PerspectiveCamera(aspect=1.5, position=(10.0, 10.0, 10.0), projectionMatrix=(1.0, 0.0, 0.0, 0.…

### Матрицы преобразования

Местоположение и ориентация любой заданной сетки сохраняется в ее [ матрице преобразований](https://en.wikipedia.org/wiki/Transformation_matrix). 

Матрица преобразования обычно используется в графических приложениях, может описывать положение, ориентацию, масштабирование и наклон объекта, сетку точек. 

Матрица преобразования, которая описывает только вращение и позицию принимает такой вид:

$$
   \mathbf{T} = \begin{bmatrix}
   {}^N\mathbf{C}^B & \bar{0} \\
   \bar{r}^{P/O} & 1
   \end{bmatrix} \quad \mathbf{T}\in \mathbb{R}^{4x4}
$$

Здесь матрица поворотов сетки «B» по отношению к глобальной системе отсчета сцены «N», хранится в первых трех строках и столбцах, вектор положения точки $P$ относительно $O$ хранится в трех первых колонках нижней записи. Если нет поворотов или вращений, матрица поворота становится единичной. 
Эта матрица хранится в атрибуте [`matrix`](https://pythreejs.readthedocs.io/en/stable/api/core/Object3D_autogen.html#pythreejs.Object3D.matrix):

In [33]:
cyl_mesh.matrix

(1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 3.0,
 3.0,
 3.0,
 1.0)

Обратите внимание, что матрица 4x4 хранится «сведенной» в одном списке из 16 значений.

In [13]:
len(cyl_mesh.matrix)

16

Можно превратить его в массив Numpy, используя [`reshape()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.reshape.html#numpy.ndarray.reshape")это и [`flatten()`](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flatten.html#numpy.ndarray.flatten")

In [14]:
np.array(cyl_mesh.matrix).reshape(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [3., 3., 3., 1.]])

In [15]:
np.array(cyl_mesh.matrix).reshape(4, 4).flatten()

array([1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 3., 3., 3., 1.])

Каждая сетка/геометрия имеет свою собственную локальную систему координат и начало координат. 

Для цилиндра, начало координат находится в геометрическом центре, а ось цилиндра равна выровнено по своей локальной оси Y. 

Для нашего тела A, нам нужен цилиндр, у которого ось по вектору x. 

Поэтому нужно создать новую систему отсчета, в которой ее единичный вектор Y совмещен с $\hat{a_x}$. 

In [16]:
Ac = me.ReferenceFrame('Ac')
Ac.orient_axis(A, sm.pi/2, A.z)

Теперь можно создать матрицу транформации для $A_c$ и $A_o$.
* $A_o$ выравнивается с оригинальной сеткой цилиндра
* $A_c$ выравнен с собственной системой координат.


In [17]:
TA = sm.eye(4)
TA[:3, :3] = Ac.dcm(N)
TA[3, :3] = sm.transpose(Ao.pos_from(O).to_matrix(N))
TA

Matrix([
[   -sin(q1(t)),     cos(q1(t)), 0, 0],
[   -cos(q1(t)),    -sin(q1(t)), 0, 0],
[             0,              0, 1, 0],
[l*cos(q1(t))/2, l*sin(q1(t))/2, 0, 1]])

Ось «B» уже правильно совмещена с локальной системой координат геометрии цилиндра поэтому нам не нужно вводить новую систему отсчета для его матрицы преобразования.

In [18]:
TB = sm.eye(4)
TB[:3, :3] = B.dcm(N)
TB[3, :3] = sm.transpose(Bo.pos_from(O).to_matrix(N))
TB

Matrix([
[            cos(q1(t)),             sin(q1(t)),          0, 0],
[-sin(q1(t))*cos(q2(t)),  cos(q1(t))*cos(q2(t)), sin(q2(t)), 0],
[ sin(q1(t))*sin(q2(t)), -sin(q2(t))*cos(q1(t)), cos(q2(t)), 0],
[          l*cos(q1(t)),           l*sin(q1(t)),          0, 1]])

Наконец, мы добавим сферическую сетку, чтобы показать местоположение точки Q. 

Мы можем выбрать любую систему отсчета, потому что сфера выглядит одинаково со всех сторон, но возьмем систему координат $B$, т.к. надо описать точку, как скользящую по стержню $B$. 

Этот выбор сыграет роль в улучшении визуализации локальных осей координат в финальном варианте анимации.

In [19]:
TQ = sm.eye(4)
TQ[:3, :3] = B.dcm(N)
TQ[3, :3] = sm.transpose(Q.pos_from(O).to_matrix(N))
TQ

Matrix([
[                                cos(q1(t)),                                 sin(q1(t)),                0, 0],
[                    -sin(q1(t))*cos(q2(t)),                      cos(q1(t))*cos(q2(t)),       sin(q2(t)), 0],
[                     sin(q1(t))*sin(q2(t)),                     -sin(q2(t))*cos(q1(t)),       cos(q2(t)), 0],
[l*cos(q1(t)) - q3(t)*sin(q1(t))*cos(q2(t)), l*sin(q1(t)) + q3(t)*cos(q1(t))*cos(q2(t)), q3(t)*sin(q2(t)), 1]])

Теперь, когда у нас есть матрицы символических преобразований, давайте выпрямим их, чтобы они были в той форме, которая нужна для Three.js: 

In [20]:
TA = TA.reshape(16, 1)
TB = TB.reshape(16, 1)
TQ = TQ.reshape(16, 1)

In [21]:
TA

Matrix([
[   -sin(q1(t))],
[    cos(q1(t))],
[             0],
[             0],
[   -cos(q1(t))],
[   -sin(q1(t))],
[             0],
[             0],
[             0],
[             0],
[             1],
[             0],
[l*cos(q1(t))/2],
[l*sin(q1(t))/2],
[             0],
[             1]])

Теперь функция для численной оценки заданных матриц преобразования, обобщенные координат и константы системы: 

In [22]:
eval_transform = sm.lambdify((q, p), (TA, TB, TQ))
eval_transform(q_vals, p_vals)

(array([[-0.42261826],
        [ 0.90630779],
        [ 0.        ],
        [ 0.        ],
        [-0.90630779],
        [-0.42261826],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 1.        ],
        [ 0.        ],
        [ 0.27189234],
        [ 0.12678548],
        [ 0.        ],
        [ 1.        ]]),
 array([[ 0.90630779],
        [ 0.42261826],
        [ 0.        ],
        [ 0.        ],
        [-0.42101007],
        [ 0.90285901],
        [ 0.08715574],
        [ 0.        ],
        [ 0.03683361],
        [-0.07898993],
        [ 0.9961947 ],
        [ 0.        ],
        [ 0.54378467],
        [ 0.25357096],
        [ 0.        ],
        [ 1.        ]]),
 array([[ 0.90630779],
        [ 0.42261826],
        [ 0.        ],
        [ 0.        ],
        [-0.42101007],
        [ 0.90285901],
        [ 0.08715574],
        [ 0.        ],
        [ 0.03683361],
        [-0.07898993],
        [ 0.9961947 ],
       

Наконец, создадим список списков для матриц преобразования ts, 
так как это форма, необходимая для данных анимации ниже: 

In [35]:
TAs = []
TBs = []
TQs = []

for xi in xs:
    TAi, TBi, TQi = eval_transform(xi[:3], p_vals)
    TAs.append(TAi.squeeze().tolist())
    TBs.append(TBi.squeeze().tolist())
    TQs.append(TQi.squeeze().tolist())

In [36]:
TAs[:2]

[[-0.42261826174069944,
  0.9063077870366499,
  0.0,
  0.0,
  -0.9063077870366499,
  -0.42261826174069944,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.27189233611099495,
  0.12678547852220984,
  0.0,
  1.0],
 [-0.4187739215332694,
  0.9080905255775148,
  0.0,
  0.0,
  -0.9080905255775148,
  -0.4187739215332694,
  0.0,
  0.0,
  0.0,
  0.0,
  1.0,
  0.0,
  0.2724271576732544,
  0.12563217645998082,
  0.0,
  1.0]]

### Определения геометрии и сетки

Создадим два цилиндра для стержней — A и B и сферу для частицы Q: 

In [25]:
rod_radius = p_vals[3]/20  # l/20
sphere_radius = p_vals[3]/16  # l/16

geom_A = p3js.CylinderGeometry(
    radiusTop=rod_radius,
    radiusBottom=rod_radius,
    height=p_vals[3],  # l
)

geom_B = p3js.CylinderGeometry(
    radiusTop=rod_radius,
    radiusBottom=rod_radius,
    height=p_vals[3],  # l
)

geom_Q = p3js.SphereGeometry(radius=sphere_radius)

Теперь создадим сетки для каждого тела и добавим в них материал разного цвета. 

Каждой сетке потребуется уникальное имя, чтобы мы могли связать информация анимации с правильным объектом. 

После создания сетки выключаем атрибут [`matrixAutoUpdate`](https://pythreejs.readthedocs.io/en/stable/api/core/Object3D_autogen.html#pythreejs.Object3D.matrixAutoUpdate) на, чтобы можно было вручную укажите матрицу преобразования во время анимации. Наконец, добавим локальные оси координат для каждой сетки и установите матрицу преобразования в первоначальную конфигурацию.

In [26]:
arrow_length = 0.2

mesh_A = p3js.Mesh(
    geometry=geom_A,
    material=p3js.MeshStandardMaterial(color='red'),
    name='mesh_A',
)
mesh_A.matrixAutoUpdate = False
mesh_A.add(p3js.AxesHelper(arrow_length))
mesh_A.matrix = TAs[0]

mesh_B = p3js.Mesh(
    geometry=geom_B,
    material=p3js.MeshStandardMaterial(color='blue'),
    name='mesh_B',
)
mesh_B.matrixAutoUpdate = False
mesh_B.add(p3js.AxesHelper(arrow_length))
mesh_B.matrix = TBs[0]

mesh_Q = p3js.Mesh(
    geometry=geom_Q,
    material=p3js.MeshStandardMaterial(color='green'),
    name='mesh_Q',
)
mesh_Q.matrixAutoUpdate = False
mesh_Q.add(p3js.AxesHelper(arrow_length))
mesh_Q.matrix = TQs[0]

### Настройка сцены 

Теперь создаем сцену и рендерер, включаем камеру, освещение, оси координат и все сетки. 

In [27]:
view_width = 600
view_height = 400

camera = p3js.PerspectiveCamera(position=[1.5, 0.6, 1],
                                up=[-1.0, 0.0, 0.0],
                                aspect=view_width/view_height)

key_light = p3js.DirectionalLight(position=[0, 10, 10])
ambient_light = p3js.AmbientLight()

axes = p3js.AxesHelper()

children = [mesh_A, mesh_B, mesh_Q, axes, camera, key_light, ambient_light]

scene = p3js.Scene(children=children)

controller = p3js.OrbitControls(controlling=camera)
renderer = p3js.Renderer(camera=camera, scene=scene, controls=[controller],
                         width=view_width, height=view_height)

### Настройка анимации 

`Three.js` для анимации использует концепцию «трека» для отслеживания данных, которые изменяются с течением времени.

[`VectorKeyframeTrack`](https://pythreejs.readthedocs.io/en/stable/api/animation/tracks/VectorKeyframeTrack_autogen.html#pythreejs.VectorKeyframeTrack) можно использовать, чтобы  связать изменяющиеся во времени матрицы преобразования с определенной сеткой. 

Создаваем «трек» для каждой сетки. 

In [28]:
track_A = p3js.VectorKeyframeTrack(
    name="scene/mesh_A.matrix",
    times=ts,
    values=TAs
)

track_B = p3js.VectorKeyframeTrack(
    name="scene/mesh_B.matrix",
    times=ts,
    values=TBs
)

track_Q = p3js.VectorKeyframeTrack(
    name="scene/mesh_Q.matrix",
    times=ts,
    values=TQs
)

/mnt/work2/artur/ipywidget-wtf-latex/.venv/lib64/python3.11/site-packages/pythreejs/traits.py:257: UserWarning: 64-bit data types not supported for WebGL data, casting to 32-bit.
  warnings.warn('64-bit data types not supported for WebGL '


Создаем [`AnimationAction`](https://pythreejs.readthedocs.io/en/stable/api/animation/AnimationAction_autogen.html#pythreejs.AnimationAction) что связывает треки к кнопке воспроизведения/паузы и связывают ее со сценой.

In [29]:
tracks = [track_B, track_A, track_Q]
duration = ts[-1] - ts[0]
clip = p3js.AnimationClip(tracks=tracks, duration=duration)
action = p3js.AnimationAction(p3js.AnimationMixer(scene), clip, scene)

Дополнительную информацию о настройке анимации с помощью pythreejs можно найти в [их документация](https://pythreejs.readthedocs.io/en/stable/examples/Animation.html).

### Анимированная интерактивная 3D-визуализация 

Теперь, когда сцена и анимация определены, рендерер и анимация элементы управления могут отображаться:

In [30]:
renderer

Renderer(camera=PerspectiveCamera(aspect=1.5, position=(1.5, 0.6, 1.0), projectionMatrix=(1.4296712803397058, …

In [31]:
action

AnimationAction(clip=AnimationClip(duration=10.0, tracks=(VectorKeyframeTrack(name='scene/mesh_B.matrix', time…

Оси, прикрепленные к инерциальной системе отсчета и каждой сетке, являются локальными. система координат этого объекта. Ось X — красная, ось Y — зеленая, Ось Z — синяя.

Анимацию можно использовать для подтверждения реалистичного движения системы нескольких тел и визуально исследовать различные движения, которые могут произойти. 